version: '3'

services:

  runner-node:
    # image: marianodim/dockerimagesandtools:node
    image: marianodim/dockerimagesandtools
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - /home/madim/Escritorio/projects/bnbhold:/app
    environment:
      - GH_REPOSITORY=https://github.com/mariano-dim/bnbhold
      - GH_RUNNER_TOKEN=AAVPUP74JIQURCVEPXJITC3A7WRW2
      - GH_RUNNER_LABELS=node
    restart: unless-stopped
